### ISSUE TITLE
Saving a PDF document

### ISSUE THREAD

**Issue by remil19** [wallabag/wallabag#116]
J'ai essayé d'ajouter un pdf qui s'était ouvert dans mon navigateur via pdf.js à poche, mais celui-ci l'enregistre comme du texte brut et sans titre. Ce serait bien qu'il enregistre un titre et qu'il l'ouvre dans un onglet quand on clique dessus.

**Comment by j0k3r** [comment]
For now, instead of storing the pdf itself, we provide a text version of it: https://github.com/j0k3r/graby/pull/16

**Comment by nicosomb** [comment]
Done by @j0k3r in graby :+1:

**Comment by Burning-Daylight** [comment]
I tried saving PDF-url with wallabag v2.0, but I get " wallabag can't retrieve contents for this article. Please report this issue to us. " error. Would be great if wallabag downloaded the original PDF and stored it locally for future reading.

**Comment by nicosomb** [comment]
Can you open a new issue for that please?

**Comment by toobluescientist** [comment]
> I tried saving PDF-url with wallabag v2.0.1, but I get " wallabag can't retrieve contents for this article. Please report this issue to us. " error. Would be great if wallabag downloaded the original PDF and stored it locally for future reading.

Hey, I have the same trouble as you. For me, I still cannot save PDF from a PDF url onto Wallabag. If it saves, sometimes the text is just unreadable. How is it now for you?
