### ISSUE TITLE
Installation on shared webhosting

### ISSUE THREAD

**Issue by LeBaux** [wallabag/wallabag#1479]
Hi, most of us do not have VPS or managed servers, but only regular webhosting like 1&1  or godaddy. It does not look easy to install wallabag on those, and the documentation only shows  how to do it tru terminal. Is it possible to install it just by using PHPmyADMIN and FTP? Thanks!

**Comment by j0k3r** [comment]
Are you talking about v1 or v2 ?

**Comment by SweetLion** [comment]
Support of Softaculous, cPanel and Docker would be awesome. Do you have any plans regarding these platforms? Thank you very much, I love wallabag 😍

**Comment by robertabramski** [comment]
+1 for Docker.

**Comment by tcitworld** [comment]
Docker is available here for now : https://github.com/bobmaerten/docker-wallabag and we have [an entry](https://www.softaculous.com/softaculous/apps/others/wallabag) on Softaculous.

**Comment by robertabramski** [comment]
I tested out this one; it didn't work for me. It wouldn't accept the default password after the build. This [one](https://hub.docker.com/r/neosar/wallabag-docker/) did work for me, but this is for v1. Is v2 stable enough for a Docker project?

**Comment by tcitworld** [comment]
Ping @bobmaerten about Docker.

I wouldn't advise you to try to build anything serious on v2 until the beta states, but I definitely encourage you to have a look on how it goes. :)

**Comment by nicosomb** [comment]
We published a docker-composer in our v2 branch file thanks to @FabienM. 
Can you have a look to it? And tell us if eveything looks fine for you

**Comment by bobmaerten** [comment]
I checked the `docker-compose.yml` file and there are some misconceptions about the standard nginx image configuration (default config files locations, standard logs management), but nothing serious.

The docker-compose seems to be set for prod and also dev, but best practices recommand like something simpler for production image releases, with different image tags depending on which database is prefered (wallabag:sqlite, wallabag:pgsql, wallbag:mariadb).

But to be quite honest, I didn't manage to simply make wallabag run either with or without docker stack : necessity to d/l vendor.zip as #1623 suggests, problems with missing parameter.yml on `php bin/console wallabag:install`. I thought the docker set up would have managed thoses configuration steps.

**Comment by nicosomb** [comment]
@LeBaux Are you talking about v1 or v2 ?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by kaktux** [comment]
> Hi, most of us do not have VPS or managed servers, but only regular webhosting like 1&1 or godaddy. It does not look easy to install wallabag on those, and the documentation only shows how to do it tru terminal. Is it possible to install it just by using PHPmyADMIN and FTP? Thanks!

Where in this thread is the first post answered? Can'T find that. Docker, Softacolous etc. is not per se available on any shared hoster - somehow the first question drifted afar with the first answer.
So yeah: issue still occurs.

So - i currently got the same problem. I got a "normal" webhoster (Meaning: can create databases, subdomains, phpmyadmin, choose php-version - all via hosting control panel (in my case plesk onyx)), Basically i can upload the files via ftp where i want to install wallabag on my subdomain (wallabag.mydomain.com) . 
So no command line or tinkering/editing php, apache and stuff like that.

All other self hostable programms i know can easily be installed by 
a) download program
b) copy/move/unpack onto webfolder via ftp
c) browse to webfolder where you just moved the files into -> an installer or similar occurs
done

I read probably all howtos you can find on the web now - but i still don't know how to get this done on normal webhosting.
According to my hoster my webspace fullfills all requirements for wallabag - and as this was true for other programs i have there this should be right (next cloud, fresh rss).

Can anyone give hints (or a step by step for dummies ;) ) how (if possible) to install wallabag on a simple webhoster?
