### ISSUE TITLE
Wallabag is fetching 'Cookie Approval Text' instead of article content

### ISSUE THREAD

**Issue by DonUber** [wallabag/wallabag#2428]
For a Dutch newspaper when saving to my wallabag, it fetches the text for cookie approval instead of the content of the article. Using Pocket this problem is not present.

Example of an article giving this problem: http://www.nrc.nl/nieuws/2016/10/02/de-nederlandse-school-wanorde-onrust-en-lawaai-4566603-a1524441

The fetched text is: 
> NRC Media Holding BV maakt gebruik van cookies en daarmee vergelijkbare technieken. www.nrc.nl gebruikt functionele en analytische cookies om u een optimale bezoekerservaring te bieden. Bovendien plaatsen derde partijen tracking cookies om u gepersonaliseerde advertenties te tonen en om buiten de website van NRC relevante aanbiedingen te doen. Ook worden er tracking cookies geplaatst door social media-netwerken. Uw internetgedrag kan door deze derden gevolgd worden door middel van deze tracking cookies. Door hiernaast op akkoord te klikken, of door gebruik te blijven maken van deze website gaat u hiermee akkoord.

**Comment by j0k3r** [comment]
Should be fixed in the next release

**Comment by guyspronck** [comment]
To not create a new issue about the same problem, similar issue with https://tweakers.net/nieuws/119975/google-brengt-android-wear-20-begin-februari-uit.html
(Or any other article from tweakers.net). They have a cookiewall of which the text gets displayed.

**Comment by j0k3r** [comment]
@guyspronck the article looks great on my side, no cookie content:
![image](https://cloud.githubusercontent.com/assets/62333/21882497/0116504a-d8ab-11e6-8593-5750dede761a.png)

**Comment by guyspronck** [comment]
This is the result I get:
![image](https://cloud.githubusercontent.com/assets/8409187/21882688/ec44a328-d8ab-11e6-8cd7-9d021f5d7aff.png)

I'll try the tweakers.net.txt!

**Comment by guyspronck** [comment]
Tried this and it didn't resolve the issue for me. Seems like its redirecting to a separate cookiewall page. I'm running in Docker if that adds anything.

**Comment by j0k3r** [comment]
Could you try adding `http_header(user-agent): PHP/5.3` ?

**Comment by guyspronck** [comment]
Doesn't seem to work for me. Still getting the cookie wall text as result.
