### ISSUE TITLE
https redirect with htaccess 

### ISSUE THREAD

**Issue by tristan-k** [wallabag/wallabag#534]
I'm using a redirect with .htaccess file for my provider all-inkl.com, it looks like this:

```<IfModule mod_rewrite.c>
	RewriteEngine on
	# Falls kein HTTPS aufegrufen wurde und die Anfrage nicht vom SSL-Proxy kommt 
        # -> auf SSL weiterleiten
	RewriteCond %{HTTPS} off
	RewriteCond %{HTTP:X-FORWARDED-SERVER} !^ssl-account\.com$ [NC]
	RewriteRule ^(.*)$ https://ssl-account.com/%{HTTP_HOST}/$1 [R=301,L]
</IfModule>```

It works, but it isnt possible to add articles anymore. Wallabag says:

```error during insertion : the link wasn't added```

 Any hints?


<!---
@huboard:{"milestone_order":534.0}
-->

**Comment by nilsws** [comment]
I am having the same problem as described by @TheEPOCH . The hosting provider is HostEurope. Wallabag works fine without SSL but styling is missing when accessing it via the SSL-Proxy, and when trying to login, I get redirected from https://ssl.webpack.de/wpXXXXX.server-he.de/wallabag/ to https://ssl.webpack.de/wallabag/ which does not exist. Other web apps like Owncloud work fine with the same proxy on the same webspace, so I don't think it's a problem in the global htaccess file.

**Comment by steppy** [comment]
The same issue occured for me. I fixed it for myself in the "Tools"-class:

/inc/poche/Tools.class.php

 I replaced Line 69:
 "$host = (isset($_SERVER['HTTP_X_FORWARDED_HOST']) ? $_SERVER['HTTP_X_FORWARDED_HOST'] : (isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : $_SERVER['SERVER_NAME']));"

by:
if (isset($_SERVER['HTTP_X_FORWARDED_HOST'])) {
			$host = $_SERVER['HTTP_X_FORWARDED_HOST'];
		}
		
		if (isset($_SERVER['HTTP_HOST'])) {
			$host = ((isset($host)) ? $host . '/' . $_SERVER['HTTP_HOST'] : $_SERVER['HTTP_HOST']);
		} else {
			$host = ((isset($host)) ? $host . '/' . $_SERVER['SERVER_NAME'] : $_SERVER['SERVER_NAME']);
		}

I never dealt with PHP ever before, so I am unsure if the implementation is well done. However all cases nnow work for me (usual http/https as well as SSL Proxy).

**Comment by nilsws** [comment]
Yeah, this fix doesn't work for me, unfortunately.

**Comment by steppy** [comment]
@nilsws
You also installed wallabag in a subfolder as I see (https://ssl.webpack.de/wpXXXXX.server-he.de/wallabag/). As I said this also does not work for me. However installing directly in https://ssl.webpack.de/wpXXXXX.server-he.de/ shoudl work now. For the subfolder case it would be nice to have a fix.

I saw how owncloud deals with reverse ssl proxys. They have extra parameters for this case:
http://doc.owncloud.org/server/6.0/admin_manual/configuration/configuration_reverseproxy.html
http://all-inkl.com/wichtig/anleitungen/skripte/cloud/owncloud/owncloud-mit-ssl-proxy-verbinden_391.html

Maybe this would be a solution for wallabag as well?

**Comment by nilsws** [comment]
@steppy , I've tried moving it to the root directory, but it doesn't seem to make a difference. I also tried pointing a subdomain to the wallabag-directory, which translates into this for the SSL-proxy: https://ssl.webpack.de/wallabag.domain.com/ -- no success. I wonder how other folks are using wallabag if you can't get an SSL connection to it?

**Comment by nilsws** [comment]
Just upgraded to 1.9.1 and CSS is still broken when using an SSL proxy on Hosteurope.

**Comment by nilsws** [comment]
Check https://ssl.webpack.de/wallabag.weisensee.me/ to see what I mean.

**Comment by j0k3r** [comment]
It seems that css path are:

```
http://ssl.webpack.de/themes/baggy/css/ratatouille.css
```

but should be:
```
https://ssl.webpack.de/wallabag.weisensee.me/themes/baggy/css/ratatouille.css
```

Problem might be in `Tools::getPocheUrl` I guess.

**Comment by tcitworld** [comment]
Hmm. I can put an optional constant in the config file to force the base URL to be detected. Of course, if I find the time, i'll try to fix the getPocheUrl function. We'll see.

**Comment by nilsws** [comment]
That would be great, because I don't want to switch from Instapaper as long as I can't get a secure connection to my wallabag installation. If there's any quick fix I can do myself by editing a config file, please let me know. Thanks!

**Comment by nicosomb** [comment]
This issue affects wallabag v1. This version won't move anymore.
